#!/bin/bash

function usage() {

cat << EOF
Commits changes made in the current module as well as it's submodules

Usage:
git ccommit [-r] [commit-options] 

Flags:
- -r : Recurses through all submodules
EOF
exit 0;
}

RECURSE=false
if [[ "$@" == *--help* ]]; then
  usage
fi

if [ "$1" == "-r" ]; then
    RECURSE=true
    shift
fi

if ($RECURSE); then
    echo "Commiting recusively through submodules"
    git submodule foreach --recursive git commit "$@"
else
    echo "Commiting submodules"
    git submodule foreach git commit "$@"
fi

MODLIST=$(git submodule --quiet foreach 'echo $name')

echo "Updating submodule references"
for module in $MODLIST; do

    git add $module

done

echo "Commiting current module"
git commit "$@"

